---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-setup
  namespace: argocd
spec:
  destination:
    #namespace: spring-petclinic
    server: "https://kubernetes.default.svc"
  source:
    path: prod
    repoURL: "https://github.com/harivemula/spring-petclinic-cloud-deploy.git"
    targetRevision: HEAD
  project: spring-petclinic
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    #syncOptions:
    #  - CreateNamespace=true