apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wavefront
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: spring-petclinic
    server: "https://kubernetes.default.svc"
  source:
    path: prod/apps/wavefront
    repoURL: "https://github.com/harivemula/spring-petclinic-cloud-deploy.git"
    targetRevision: HEAD
  project: spring-petclinic
  syncPolicy:
    automated:
      selfHeal: true
      prune: true