---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: spring-petclinic
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 1001
      min: 1001
    rule: MustRunAs
  requiredDropCapabilities:
  - ALL
  runAsUser:
    ranges:
    - max: 1001
      min: 1001
    rule: MustRunAs
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 1001
      min: 1001
    rule: MustRunAs
  volumes:
  - configMap
  - secret
  - emptyDir
  - persistentVolumeClaim

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spring-petclinic
  namespace: spring-petclinic
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resourceNames:
  - spring-petclinic
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-petclinic
  namespace: spring-petclinic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spring-petclinic
subjects:
- kind: ServiceAccount
  name: default
  namespace: spring-petclinic

